; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0B6B6EDD-4A0F-4E0C-BCEB-A0C638FF6C8E}
AppName=Open Chess
AppVersion=1.0.1
AppPublisher=Code A Software
AppPublisherURL=https://ca-soft.net/
AppSupportURL=https://ca-soft.net/
AppUpdatesURL=https://ca-soft.net/
DefaultDirName={autopf}\OpenChess
UninstallDisplayIcon={app}\OpenChess.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=Open Chess Setup
OutputDir=bin\Store\net10.0-windows\publish\
SetupIconFile=icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "bin\Release\net10.0-windows\publish\de\*"; DestDir: "{app}\de"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "bin\Release\net10.0-windows\publish\resources\*"; DestDir: "{app}\resources"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "bin\Release\net10.0-windows\publish\OpenChess.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\OpenChess.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\OpenChess.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\OpenChess.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\OpenChess.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
; Shared DLL
Source: "bin\Release\net10.0-windows\publish\Chess.NET.Shared.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Chess.NET.Shared.pdb"; DestDir: "{app}"; Flags: ignoreversion

; SignalR DLLs
Source: "bin\Release\net10.0-windows\publish\Microsoft.AspNetCore.Connections.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.AspNetCore.Http.Connections.Client.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.AspNetCore.Http.Connections.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.AspNetCore.SignalR.Client.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.AspNetCore.SignalR.Client.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.AspNetCore.SignalR.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.AspNetCore.SignalR.Protocols.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.Extensions.DependencyInjection.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.Extensions.DependencyInjection.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.Extensions.Features.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.Extensions.Logging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.Extensions.Options.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0-windows\publish\Microsoft.Extensions.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\OpenChess"; Filename: "{app}\OpenChess.exe"
Name: "{autodesktop}\OpenChess"; Filename: "{app}\OpenChess.exe"; Tasks: desktopicon

