//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chess.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string strAbout {
            get {
                return ResourceManager.GetString("strAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programmed by Andreas Leopold ähnelt.
        /// </summary>
        public static string strAboutLine1 {
            get {
                return ResourceManager.GetString("strAboutLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Promote To Queen ähnelt.
        /// </summary>
        public static string strAutoPromote {
            get {
                return ResourceManager.GetString("strAutoPromote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting Position ähnelt.
        /// </summary>
        public static string strBeginPosition {
            get {
                return ResourceManager.GetString("strBeginPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Black ähnelt.
        /// </summary>
        public static string strBlack {
            get {
                return ResourceManager.GetString("strBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checkmate! ähnelt.
        /// </summary>
        public static string strCheckmate {
            get {
                return ResourceManager.GetString("strCheckmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Difficulty: ähnelt.
        /// </summary>
        public static string strDifficulty {
            get {
                return ResourceManager.GetString("strDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Easy ähnelt.
        /// </summary>
        public static string strDifficulty_Easy {
            get {
                return ResourceManager.GetString("strDifficulty_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hard ähnelt.
        /// </summary>
        public static string strDifficulty_Hard {
            get {
                return ResourceManager.GetString("strDifficulty_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Middle ähnelt.
        /// </summary>
        public static string strDifficulty_Middle {
            get {
                return ResourceManager.GetString("strDifficulty_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnect! ähnelt.
        /// </summary>
        public static string strDisconnect {
            get {
                return ResourceManager.GetString("strDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw ähnelt.
        /// </summary>
        public static string strDraw {
            get {
                return ResourceManager.GetString("strDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elo: ähnelt.
        /// </summary>
        public static string strElo {
            get {
                return ResourceManager.GetString("strElo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to connect to chess server: {0} ähnelt.
        /// </summary>
        public static string strFailedToConnectToServer {
            get {
                return ResourceManager.GetString("strFailedToConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load settings! ähnelt.
        /// </summary>
        public static string strFailedToLoadSettings {
            get {
                return ResourceManager.GetString("strFailedToLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to make move or server did not accept this move: {0} ähnelt.
        /// </summary>
        public static string strFailedToMove {
            get {
                return ResourceManager.GetString("strFailedToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to open hyperlink {0}: {1} ähnelt.
        /// </summary>
        public static string strFailedToOpenHyperlink {
            get {
                return ResourceManager.GetString("strFailedToOpenHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to resign: {0} ähnelt.
        /// </summary>
        public static string strFailedToResign {
            get {
                return ResourceManager.GetString("strFailedToResign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to save settings! ähnelt.
        /// </summary>
        public static string strFailedToSaveSettings {
            get {
                return ResourceManager.GetString("strFailedToSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 50-Move Rule! ähnelt.
        /// </summary>
        public static string strFiftyMoveRule {
            get {
                return ResourceManager.GetString("strFiftyMoveRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game Over ähnelt.
        /// </summary>
        public static string strGameOver {
            get {
                return ResourceManager.GetString("strGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game tied! ähnelt.
        /// </summary>
        public static string strGameOver_Stalemate {
            get {
                return ResourceManager.GetString("strGameOver_Stalemate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The game is a draw, no legal move possible (stalemate)! ähnelt.
        /// </summary>
        public static string strGameOver_StalemateText {
            get {
                return ResourceManager.GetString("strGameOver_StalemateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game won! ähnelt.
        /// </summary>
        public static string strGameOver_Win {
            get {
                return ResourceManager.GetString("strGameOver_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} won the game by checkmate! ähnelt.
        /// </summary>
        public static string strGameOver_WinMessage {
            get {
                return ResourceManager.GetString("strGameOver_WinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die here ähnelt.
        /// </summary>
        public static string strHere {
            get {
                return ResourceManager.GetString("strHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insufficient Material ähnelt.
        /// </summary>
        public static string strInsufficientCheckmatingMaterial {
            get {
                return ResourceManager.GetString("strInsufficientCheckmatingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jump to end ähnelt.
        /// </summary>
        public static string strJumpToEndTooltip {
            get {
                return ResourceManager.GetString("strJumpToEndTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jump to start ähnelt.
        /// </summary>
        public static string strJumpToStartTooltip {
            get {
                return ResourceManager.GetString("strJumpToStartTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left ähnelt.
        /// </summary>
        public static string strLeft {
            get {
                return ResourceManager.GetString("strLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string strMenu_About {
            get {
                return ResourceManager.GetString("strMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string strMenu_Exit {
            get {
                return ResourceManager.GetString("strMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Game ähnelt.
        /// </summary>
        public static string strMenu_Game {
            get {
                return ResourceManager.GetString("strMenu_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Moves ähnelt.
        /// </summary>
        public static string strMenu_Moves {
            get {
                return ResourceManager.GetString("strMenu_Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mirror Board ähnelt.
        /// </summary>
        public static string strMirrorBoard {
            get {
                return ResourceManager.GetString("strMirrorBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Moves: ähnelt.
        /// </summary>
        public static string strMoves {
            get {
                return ResourceManager.GetString("strMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Game ähnelt.
        /// </summary>
        public static string strNewGame {
            get {
                return ResourceManager.GetString("strNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opponent: ähnelt.
        /// </summary>
        public static string strOpponent {
            get {
                return ResourceManager.GetString("strOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string strOpponent_None {
            get {
                return ResourceManager.GetString("strOpponent_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online ähnelt.
        /// </summary>
        public static string strOpponent_Online {
            get {
                return ResourceManager.GetString("strOpponent_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stockfish (Bot) ähnelt.
        /// </summary>
        public static string strOpponent_Stockfish {
            get {
                return ResourceManager.GetString("strOpponent_Stockfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stupido (Bot) ähnelt.
        /// </summary>
        public static string strOpponent_StupidoBot {
            get {
                return ResourceManager.GetString("strOpponent_StupidoBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path: ähnelt.
        /// </summary>
        public static string strPath {
            get {
                return ResourceManager.GetString("strPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player 1 ähnelt.
        /// </summary>
        public static string strPlayer1 {
            get {
                return ResourceManager.GetString("strPlayer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player 2 ähnelt.
        /// </summary>
        public static string strPlayer2 {
            get {
                return ResourceManager.GetString("strPlayer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string strPlayerName {
            get {
                return ResourceManager.GetString("strPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die due to ähnelt.
        /// </summary>
        public static string strPlayerWinsDueTo {
            get {
                return ResourceManager.GetString("strPlayerWinsDueTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wins with ähnelt.
        /// </summary>
        public static string strPlayerWinsWith {
            get {
                return ResourceManager.GetString("strPlayerWinsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play sounds ähnelt.
        /// </summary>
        public static string strPlaySounds {
            get {
                return ResourceManager.GetString("strPlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Promote Pawn ähnelt.
        /// </summary>
        public static string strPromotePawn {
            get {
                return ResourceManager.GetString("strPromotePawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Puzzle ähnelt.
        /// </summary>
        public static string strPuzzle {
            get {
                return ResourceManager.GetString("strPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Puzzle failed! ähnelt.
        /// </summary>
        public static string strPuzzle_Failed {
            get {
                return ResourceManager.GetString("strPuzzle_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replay ähnelt.
        /// </summary>
        public static string strPuzzle_Replay {
            get {
                return ResourceManager.GetString("strPuzzle_Replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retry ähnelt.
        /// </summary>
        public static string strPuzzle_Retry {
            get {
                return ResourceManager.GetString("strPuzzle_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Puzzle solved! ähnelt.
        /// </summary>
        public static string strPuzzle_Solved {
            get {
                return ResourceManager.GetString("strPuzzle_Solved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resign ähnelt.
        /// </summary>
        public static string strResign {
            get {
                return ResourceManager.GetString("strResign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resignation! ähnelt.
        /// </summary>
        public static string strResignation {
            get {
                return ResourceManager.GetString("strResignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right ähnelt.
        /// </summary>
        public static string strRight {
            get {
                return ResourceManager.GetString("strRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string strSettings {
            get {
                return ResourceManager.GetString("strSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show next move ähnelt.
        /// </summary>
        public static string strShowNextMoveTooltip {
            get {
                return ResourceManager.GetString("strShowNextMoveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show previous move ähnelt.
        /// </summary>
        public static string strShowPreviousMoveTooltip {
            get {
                return ResourceManager.GetString("strShowPreviousMoveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stalemate! ähnelt.
        /// </summary>
        public static string strStalemate {
            get {
                return ResourceManager.GetString("strStalemate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stockfish is a UCI chess engine that you can play against! Further information and downloads are available ähnelt.
        /// </summary>
        public static string strStockfish_Explanation {
            get {
                return ResourceManager.GetString("strStockfish_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stockfish could not be found. Please ensure that you have downloaded the files correctly and that the path is set correctly in the settings! ähnelt.
        /// </summary>
        public static string strStockfishNotFound {
            get {
                return ResourceManager.GetString("strStockfishNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Threefold Repetition! ähnelt.
        /// </summary>
        public static string strThreefoldRepition {
            get {
                return ResourceManager.GetString("strThreefoldRepition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timeout! ähnelt.
        /// </summary>
        public static string strTimeout {
            get {
                return ResourceManager.GetString("strTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searching for a match ... ähnelt.
        /// </summary>
        public static string strWaiting_Content {
            get {
                return ResourceManager.GetString("strWaiting_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting ... ähnelt.
        /// </summary>
        public static string strWaiting_Title {
            get {
                return ResourceManager.GetString("strWaiting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die White ähnelt.
        /// </summary>
        public static string strWhite {
            get {
                return ResourceManager.GetString("strWhite", resourceCulture);
            }
        }
    }
}
